name: Manureva
favicon: null
layout_spectrum: 0.98808
typography_spectrum: 0.30529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96a9b7'
    - '#6287a2'
    - '#181c1b'
    - '#564f32'
    - '#81241d'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
